# PostgreSQL runtime configuration for TLS-only external access.
log_min_messages = error
listen_addresses = '*'
ssl = on
ssl_cert_file = '/var/lib/postgresql/tls/server.crt'
ssl_key_file = '/var/lib/postgresql/tls/server.key'
hba_file = '/etc/postgresql/pg_hba.conf'
password_encryption = scram-sha-256
