services:
  web:
    volumes:
      - ./src:/app/src
    command: [ "uvicorn", "src.fdr_etl.web.app:app", "--host", "0.0.0.0", "--port", "5000", "--reload", --no-access-log]

  worker:
    volumes:
      - ./src:/app/src
  superset:
    build:
      context: .
      dockerfile: Dockerfile.superset
    user: root
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_CONFIG_PATH=/app/pythonpath/superset_config.py
      - SUPERSET_FEATURE_EMBEDDED_DASHBOARD=true
      - SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY}
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@db:5432/fdr_db
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fdr_db
      - KEYCLOAK_SUPERSET_INTERNAL_URL=${KEYCLOAK_SUPERSET_INTERNAL_URL}
      - KEYCLOAK_SUPERSET_CLIENT_ID=${KEYCLOAK_SUPERSET_CLIENT_ID}
      - KEYCLOAK_SUPERSET_SECRET=${KEYCLOAK_SUPERSET_SECRET}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_ISSUER=${KEYCLOAK_ISSUER}
    depends_on:
      - db
    networks:
      - fdr_network
    volumes:
      - superset_home:/app/superset_home
      - ./superset_config.py:/app/pythonpath/superset_config.py
    extra_hosts:
      - "kc-host:host-gateway"
  keycloak:
    image: keycloak/keycloak:24.0
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-file
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
    ports:
      - "8080:8080"
    volumes:
      - ./fdr-realm.json:/opt/keycloak/data/import/fdr-realm.json
    networks:
      - fdr_network

volumes:
  superset_home: