services:
  web:
    volumes:
      - ./src:/app/src
    command: [ "uvicorn", "src.fdr_etl.web.app:app", "--host", "0.0.0.0", "--port", "5000", "--reload" ]

  worker:
    volumes:
      - ./src:/app/src
